Django/project1/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path("",views.posts_list,name='list'),
    path("<slug:slug>",views.post_page,name='page'),
]

Django/project1/project1/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home),
    path("about/",views.about),
    path('contact/',views.contact),
    path("posts/",include('posts.urls')),
    path("users/" ,include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/project1/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path("register/",views.register_view,name='register'),
    path("login/",views.login_view,name='register'),
   
]

Django/project1/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='img1.png' , blank=True)

    def __str__(self):
        return f"title: {self.title}\nbody: {self.body}\nslug: {self.slug}\ndate: {self.date}\n"
    

Django/project1/posts/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html',{'posts' : posts})

def post_page(request,slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html',{'post' : post})

Django/project1/project1/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

Django/project1/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import authenticate

# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request,"users/register.html",{'form':form})

def login_view(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(username= username,password=password)
        if user is not None:
            return redirect('posts:list')
        else:
            return render(request,"users/login.html",{'form':AuthenticationForm()})
        
    else:
        form = AuthenticationForm()
        return render(request, "users/login.html",{'form':form})
    

Django/project1/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
    {{ post.title}}
{% endblock title %}


{% block content %}
    <section>
        <img class = 'banner' src="{{ post.banner.url }}" alt="{{ post.title}}">
        <h1>{{ post.title }}</h1>
        <p>{{ post.body }}</p>
        <p>{{ post.date }}</p>

    </section>
{% endblock content %}

Django/project1/posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <section>
        <h1>Posts</h1>
         
        {% for post in posts  %}
            <article class='post'>
                <h2>
                    <a href="{% url 'posts:page' slug=post.slug %}">
                        {{ post.title }}
                    </a>
                </h2>
                <p>{{ post.body }}</p>
                <p>{{ post.date }}</p>
            </article>
        {% endfor %}
    </section>
{% endblock content %}

Django/project1/templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock title %}

{% block content %}

<section>
    <h2>About Us</h2>
    <p>This is a simple home page created to demonstrate basic HTML and CSS. You can learn more about our services and contact us through the links above.</p>
</section>

{% endblock content %}

Django/project1/templates/contact.html
{% extends "layout.html" %}

{% block title %}Contact{% endblock title %}

{% block content %}
    <section>
        <h2>Contact</h2>
        <p>You can contact us at +919876787654</p>
    </section>
{% endblock content %}

Django/project1/templates/home.html
{% extends "layout.html" %}

{% block title %}
Home
{% endblock title %}

{% block content %}
    <main>
        <section>
            <h2>About Us</h2>
            <p>This is a simple home page created to demonstrate basic HTML and CSS. You can learn more about our services and contact us through the links above.</p>
        </section>
        <section>
            <h2>Services</h2>
            <p>We offer a variety of services to cater to your needs. Stay tuned for more updates!</p>
        </section>
    </main>
{% endblock content %}

Django/project1/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title%}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <h1>Welcome to My Simple Home Page</h1>
    </header>
    <nav>
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="{% url 'posts:list' %}">Posts</a></li>
            <li><a href="/contact">Contact</a></li>
            <li><a href="{% url 'users:register' %}">User</a></li>
        </ul>
    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Simple Home Page. All rights reserved.</p>
    </footer>

</body>
</html>

Django/project1/users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
    Login User
{% endblock title %}

{% block content %}
    <h1>Login</h1>
    <form class="form-with-validation" action="/users/login/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>

{% endblock content%}

Django/project1/users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
    Register a new user
{% endblock title %}

{% block content %}
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="/users/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>

{% endblock content%}