Django/Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.index ,name='index'),
    path("users/",include('users.urls'),name='users')
]

Django/Blog/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'users'
urlpatterns = [
    path('signUp/', views.SignUpView.as_view(), name='signUp'),
    path('signIn/', views.SignInView.as_view(), name='signIn'),
    path('signOut/', LogoutView.as_view(next_page='index'), name='signOut'),
]

Django/Blog/Blog/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

Django/Blog/users/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.views import View
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView

# Create your views here.
class SignUpView(View):
    
    
    template_name = "signUp.html"

    def get(self, request, *args, **kwargs):
        form =UserCreationForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('signIn')

        return render(request, self.template_name, {"form": form})
    
    


class SignInView(LoginView):
    template_name = "signIn.html"
    # redirect_authenticated_user = True

    def get_success_url(self) -> str:
        return reverse_lazy("index")
    

# class SignOutView(LogoutView):
#     next_page = 'index'
    

Django/Blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Blog</h1>
    {% if request.user.is_authenticated %}
        

        <form method="post" action="{% url 'users:signOut' %}">
            {% csrf_token %}
            <button type="submit">SignOut</button>
        </form> 
        
    {% else %}
         <a href="{% url 'users:signUp' %}">SignUp</a>
        <br>
        <a href="{% url 'users:signIn' %}">SignIn</a>
        <br>
    {% endif %}
    
    <h1>Logged in as : {{ user }}</h1>
    {% block main %}
    {% endblock main %}
</body>
</html>

Django/Blog/users/templates/signIn.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>SignIn</h1>
    

    <form class="form-with-validation" action="/users/signIn/" method="post">
        {% csrf_token %}
        {{ form }}
        <button  class="form-submit" style = "margin-top:2rem">Submit</button>
    </form>
</body>
</html>

Django/Blog/users/templates/signUp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>SignUp</h1>
    

    <form class="form-with-validation" action="/users/signUp/" method="post">
        {% csrf_token %}
        {{ form }}
        <button  class="form-submit" style = "margin-top:2rem">Submit</button>
    </form>
    
</body>
</html>